// Integration tests: synthetic account, isolated Compose only. Never run against the main workspace.
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const { execFileSync } = require('node:child_process');
const fs = require('node:fs');
const compose = ['compose', '-p', 'frameit-workspace-review', '-f', 'tests/compose.workspace-review.yaml'];
const docker = (...args) => execFileSync('docker', [...compose, ...args], { encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'] }).trim();
const root = 'http://localhost:18080';
const results = [];
const connections = [];
const { HubConnectionBuilder, LogLevel } = require('../frontend/node_modules/@microsoft/signalr');
function totp(secret, offset = 0) {
  let bits = ''; for (const c of secret.replace(/=/g, '')) bits += 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'.indexOf(c).toString(2).padStart(5, '0');
  const bytes = Buffer.from(bits.match(/.{8}/g).map(s => parseInt(s, 2)));
  const counter = Buffer.alloc(8); counter.writeBigUInt64BE(BigInt(Math.floor(Date.now() / 30000) + offset));
  const hash = crypto.createHmac('sha1', bytes).update(counter).digest(); const at = hash[19] & 15;
  return ((hash.readUInt32BE(at) & 0x7fffffff) % 1000000).toString().padStart(6, '0');
}
function client(initial = '') {
  const jar = new Map(initial.split('; ').filter(Boolean).map(s => [s.slice(0, s.indexOf('=')), s.slice(s.indexOf('=') + 1)]));
  const cookie = () => [...jar].map(([k, v]) => `${k}=${v}`).join('; ');
  const raw = async (url, init = {}) => {
    const response = await fetch(root + url, { ...init, headers: { Cookie: cookie(), ...init.headers } });
    for (const header of response.headers.getSetCookie()) { const pair = header.split(';')[0]; const at = pair.indexOf('='); jar.set(pair.slice(0, at), pair.slice(at + 1)); }
    return response;
  };
  const call = async (url, body, expected = 200) => {
    let headers = { 'Content-Type': 'application/json' };
    if (body !== undefined) headers['X-CSRF-TOKEN'] = (await (await raw('/api/auth/csrf')).json()).token;
    let response = await raw(url, { method: body === undefined ? 'GET' : 'POST', headers, body: body === undefined ? undefined : JSON.stringify(body) });
    if (response.status === 429) { console.log('Rate limit reached; waiting for the next test window.'); await new Promise(r => setTimeout(r, 61000)); return call(url, body, expected); }
    assert.equal(response.status, expected, url);
    return expected === 204 ? null : response.headers.get('content-type')?.includes('json') ? response.json() : null;
  };
  return { cookie, call, raw };
}
async function main() {
  assert.equal((await fetch(root + '/api/health')).status, 200);
  const anon = client(); const owner = client();
  assert.equal((await owner.call('/api/auth/status')).setupRequired, true, 'Requires clean isolated auth');
  for (const path of ['/api/clients', '/api/templates', '/api/sessions', '/api/workspace/clients']) await anon.call(path, undefined, 401);
  assert.equal((await anon.raw('/api/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' })).status, 400);
  await anon.call('/api/auth/login', {}, 401);
  results.push('Anonymous catalogs blocked; mock login removed; CSRF required on login');
  const installationCode = docker('exec', '-T', 'api', 'cat', '/app/auth-state/bootstrap-token');
  const username = 'auth.test'; const password = crypto.randomBytes(24).toString('hex');
  await owner.call('/api/auth/setup', { username, password, installationCode: 'wrong' }, 401);
  await owner.call('/api/auth/setup', { username, password, installationCode });
  assert.equal((await owner.call('/api/auth/me')).isAuthenticated, false);
  await owner.call('/api/templates', undefined, 401);
  assert.equal((await owner.call('/api/auth/status')).pending, 'setup');
  const enrollment = await owner.call('/api/auth/enrollment');
  await owner.call('/api/auth/verify', { code: '99999999' }, 401);
  let { recoveryCodes } = await owner.call('/api/auth/verify', { code: totp(enrollment.secret) });
  assert.equal(recoveryCodes.length, 10);
  assert.equal((await owner.call('/api/auth/me')).isAuthenticated, true);
  assert(owner.cookie().includes('frameit.facilitator.v1='));
  await owner.call('/api/auth/setup', { username, password, installationCode }, 409);
  await owner.call('/api/auth/verify', { code: totp(enrollment.secret) }, 401);
  results.push('First owner requires installation code and TOTP; pending state resumes and grants no private access; enrollment challenge consumed');
  const dbRows = JSON.parse(docker('exec', '-T', 'db', 'psql', '-U', 'frameit_review', '-d', 'frameit_review', '-tAc', 'SELECT row_to_json(u) FROM "AspNetUsers" u'));
  assert.notEqual(dbRows.PasswordHash, password); assert(!dbRows.ProtectedTotpSecret.includes(enrollment.secret));
  const storedCodes = docker('exec', '-T', 'db', 'psql', '-U', 'frameit_review', '-d', 'frameit_review', '-tAc', 'SELECT "Id" FROM "FacilitatorRecoveryCodes"');
  for (const code of recoveryCodes) assert(!storedCodes.includes(code));
  results.push('Passwords hashed, TOTP protected with Data Protection, recovery codes stored as hashes');
  const clients = await owner.call('/api/clients');
  const templates = await owner.call('/api/templates');
  const session = await owner.call('/api/sessions', { title: 'Auth isolated integration', clientId: clients[0].id, projectId: clients[0].projects[0].id, templateId: templates[0].id }, 201);
  const participant = await anon.call(`/api/sessions/${session.id}/join`, { displayName: 'Participante sin cuenta' });
  const publicSnapshot = await anon.call(`/api/sessions/by-code/${session.accessCode}`);
  assert(publicSnapshot.id === session.id && participant.id);
  results.push('Participant joins and reads by code without facilitator login');
  const pdf = await owner.raw(`/api/sessions/${session.id}/documentation.pdf`);
  assert.equal(pdf.status, 200); assert(pdf.headers.get('content-type').includes('application/pdf'));
  const privateHub = new HubConnectionBuilder().withUrl(root + '/hubs/session', { headers: { Cookie: owner.cookie() } }).configureLogging(LogLevel.None).build();
  const publicHub = new HubConnectionBuilder().withUrl(root + '/hubs/session').configureLogging(LogLevel.None).build();
  connections.push(privateHub, publicHub);
  let privateEvents = 0, publicEvents = 0;
  privateHub.on('session-updated', () => privateEvents++); publicHub.on('session-updated', () => publicEvents++);
  await privateHub.start(); await privateHub.invoke('JoinFacilitatorSession', session.accessCode);
  await publicHub.start(); await publicHub.invoke('JoinSession', session.accessCode);
  await anon.call(`/api/sessions/${session.id}/questions`, { participantId: participant.id, question: 'Antes del cierre de acceso' });
  await new Promise(r => setTimeout(r, 300));
  assert.equal(privateEvents, 1); assert.equal(publicEvents, 1);
  const stolen = client(owner.cookie());
  await owner.call('/api/auth/logout', {}, 204);
  await stolen.call('/api/templates', undefined, 401);
  await anon.call(`/api/sessions/${session.id}/questions`, { participantId: participant.id, question: 'Después del cierre de acceso' });
  await new Promise(r => setTimeout(r, 300));
  assert.equal(privateEvents, 1); assert.equal(publicEvents, 2);
  await assert.rejects(privateHub.invoke('JoinFacilitatorSession', session.accessCode));
  await privateHub.stop(); await publicHub.stop();
  results.push('Private live connection stops receiving after logout; public collaboration continues; PDF export authenticated');
  await owner.call('/api/auth/login', { username, password });
  await owner.call('/api/templates', undefined, 401);
  await owner.call('/api/auth/verify', { code: totp(enrollment.secret, -3) }, 401);
  await owner.call('/api/auth/verify', { code: recoveryCodes.shift() });
  const other = client(); await other.call('/api/auth/login', { username, password });
  const oneUse = recoveryCodes.shift(); await other.call('/api/auth/verify', { code: oneUse });
  await other.call('/api/auth/logout', {}, 204); await other.call('/api/auth/login', { username, password });
  await other.call('/api/auth/verify', { code: oneUse }, 401);
  results.push('Password alone insufficient; expired TOTP and reused recovery rejected; copied cookie revoked on logout');
  // Rotating setup must not replace the previous authenticator until the confirmation.
  await owner.call('/api/auth/rotate', { password, code: recoveryCodes.shift() });
  const pendingNew = await owner.call('/api/auth/enrollment');
  assert.notEqual(pendingNew.secret, enrollment.secret);
  await owner.call('/api/auth/cancel', {}, 204);
  const before = JSON.parse(docker('exec', '-T', 'db', 'psql', '-U', 'frameit_review', '-d', 'frameit_review', '-tAc', 'SELECT row_to_json(u) FROM "AspNetUsers" u'));
  assert.equal(before.ProtectedTotpSecret, dbRows.ProtectedTotpSecret);
  await owner.call('/api/auth/rotate', { password, code: recoveryCodes.shift() });
  const next = await owner.call('/api/auth/enrollment');
  const oldCookie = client(owner.cookie());
  ({ recoveryCodes } = await owner.call('/api/auth/verify', { code: totp(next.secret) }));
  await oldCookie.call('/api/templates', undefined, 401);
  results.push('Authenticator rotation cancel preserves old secret; confirmation replaces it and revokes previous sessions');
  const newPassword = crypto.randomBytes(24).toString('hex');
  const previousSession = client(owner.cookie());
  await owner.call('/api/auth/password', { password, newPassword, code: recoveryCodes.shift() });
  await previousSession.call('/api/templates', undefined, 401);
  await anon.call('/api/auth/login', { username, password }, 401);
  await anon.call('/api/auth/login', { username, password: newPassword });
  const duplicateCode = recoveryCodes.shift();
  const attemptA = client(anon.cookie()), attemptB = client(anon.cookie());
  const outcomes = await Promise.all([attemptA.call('/api/auth/verify', { code: duplicateCode }).then(() => 200).catch(error => { assert.equal(error.actual, 401); return 401; }), attemptB.call('/api/auth/verify', { code: duplicateCode }).then(() => 200).catch(error => { assert.equal(error.actual, 401); return 401; })]);
  assert.deepEqual(outcomes.sort(), [200, 401]);
  results.push('Password change revokes sessions and old password; concurrent recovery/challenge consumption succeeds once');
  const lastCodes = [...recoveryCodes];
  ({ recoveryCodes } = await owner.call('/api/auth/recovery', { password: newPassword, code: recoveryCodes.shift() }));
  await anon.call('/api/auth/login', { username, password: newPassword });
  await anon.call('/api/auth/verify', { code: lastCodes.at(-1) }, 401);
  results.push('Regenerating recovery invalidates previous codes');
  docker('restart', 'api');
  for (let i = 0; i < 40; i++) { try { if ((await fetch(root + '/api/health')).status === 200) break; } catch {} await new Promise(r => setTimeout(r, 1000)); }
  assert.equal((await owner.call('/api/auth/me')).isAuthenticated, true);
  assert.equal((await owner.call('/api/auth/status')).setupRequired, false);
  results.push('API restart retains cookie validation, account and Data Protection keys');
  await owner.call('/api/auth/logout', {}, 204);
  await owner.call('/api/auth/login', { username, password: newPassword });
  const valid = totp(next.secret, 1);
  await owner.call('/api/auth/verify', { code: valid });
  await owner.call('/api/auth/logout', {}, 204);
  await owner.call('/api/auth/login', { username, password: newPassword });
  await owner.call('/api/auth/verify', { code: valid }, 401);
  results.push('TOTP time step cannot be reused on a new login challenge');
  for (let n = 0; n < 5; n++) await owner.call('/api/auth/login', { username, password: 'incorrect password' }, 401);
  await owner.call('/api/auth/login', { username, password: newPassword }, 401);
  results.push('Persistent account lockout rejects correct password after repeated failures');
  fs.mkdirSync('output/playwright/local-auth-api', { recursive: true });
  fs.writeFileSync('output/playwright/local-auth-api/results.json', JSON.stringify({ passed: results.length, results }, null, 2));
  console.log(JSON.stringify({ passed: results.length, results }, null, 2));
}
main().catch(error => { console.error(error.message); process.exitCode = 1; }).finally(() => Promise.all(connections.map(connection => connection.stop())));
