const { chromium } = require('../artifacts/npm-cache/_npx/31e32ef8478fbf80/node_modules/playwright-core');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = 'http://127.0.0.1:5175';
const out = path.join(__dirname, '../output/playwright/real-integration');
const results = [];
async function main() {
  fs.mkdirSync(out, { recursive: true });
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  try {
    const facilitator = await browser.newContext({ viewport: { width: 1440, height: 900 } });
    const participant = await browser.newContext({ viewport: { width: 390, height: 844 } });
    const page = await facilitator.newPage();
    await page.goto(root + '/sesiones?crear=1');
    await page.getByLabel('Nombre de la sesión').fill('Construimos una mejor forma de trabajar');
    // Sign-in from the sidebar must also update the form's auth hook.
    await page.locator('.workspace-sidebar').getByRole('button', { name: 'Entrar', exact: true }).click();
    await page.getByRole('button', { name: 'Crear y abrir sala' }).click();
    await page.waitForURL('**/sesion/**');
    await page.getByRole('button', { name: 'Abrir ronda', exact: true }).waitFor();
    const id = page.url().split('/').at(-1);
    const response = await facilitator.request.get(root + `/api/sessions/${id}/facilitator`);
    const session = await response.json();
    assert.equal(session.joinUrl, root + '/join/' + session.accessCode, 'The delivered join URL must open the frontend, not the API port');
    await page.screenshot({ path: path.join(out, 'facilitator-lobby.png'), fullPage: true });
    results.push('Create session from UI; sidebar login synchronizes form');
    const mobile = await participant.newPage();
    await mobile.goto(session.joinUrl);
    await mobile.getByRole('textbox', { name: 'Tu nombre o alias' }).fill('Alex');
    await mobile.getByRole('button', { name: 'Entrar a la sesión' }).click();
    await mobile.getByRole('heading', { name: 'Ya estás dentro' }).waitFor();
    await page.getByText('1 participantes', { exact: true }).waitFor();
    await page.getByRole('button', { name: 'Abrir ronda', exact: true }).click();
    const answer = mobile.getByRole('textbox', { name: 'Tu respuesta', exact: true });
    await answer.fill('Compartir conocimiento para trabajar mejor juntos.');
    await mobile.reload();
    await answer.waitFor();
    assert.equal(await answer.inputValue(), 'Compartir conocimiento para trabajar mejor juntos.');
    await mobile.getByRole('button', { name: 'Enviar respuesta', exact: true }).click();
    await mobile.getByText('Tu respuesta está guardada', { exact: true }).waitFor();
    await page.getByText('Compartir conocimiento para trabajar mejor juntos.', { exact: true }).waitFor();
    await mobile.screenshot({ path: path.join(out, 'participant-sent.png'), fullPage: true });
    results.push('Real REST/SignalR join, opening, draft reload, submission and facilitator receipt');
    const projection = await facilitator.newPage();
    await projection.setViewportSize({ width: 1280, height: 720 });
    await projection.goto(root + '/proyeccion/' + session.accessCode);
    await projection.locator('.projection-context').waitFor();
    assert.equal(await projection.getByText('Compartir conocimiento para trabajar mejor juntos.', { exact: true }).count(), 0);
    await page.getByRole('button', { name: 'Cerrar ronda', exact: true }).click();
    await page.getByRole('button', { name: 'Revelar resultados', exact: true }).click();
    await projection.getByText('Compartir conocimiento para trabajar mejor juntos.', { exact: true }).waitFor();
    await projection.screenshot({ path: path.join(out, 'projection-results.png'), fullPage: true });
    results.push('Projection with facilitator cookie only receives publicly revealed results');
    await page.getByRole('button', { name: 'Siguiente pregunta', exact: true }).click();
    await page.getByRole('button', { name: 'Abrir ronda', exact: true }).waitFor();
    await page.getByRole('button', { name: 'Abrir ronda', exact: true }).click();
    await answer.waitFor(); assert.equal(await answer.inputValue(), '');
    await answer.fill('Segundo borrador que debe sobrevivir a la desconexión.');
    await participant.setOffline(true);
    await mobile.getByText('Sin conexión · tu borrador se conserva', { exact: true }).waitFor();
    await participant.setOffline(false);
    await mobile.getByText('En directo', { exact: true }).waitFor();
    await mobile.getByRole('button', { name: 'Enviar respuesta', exact: true }).waitFor();
    assert.equal(await answer.inputValue(), 'Segundo borrador que debe sobrevivir a la desconexión.');
    await mobile.getByRole('button', { name: 'Enviar respuesta', exact: true }).click();
    await mobile.getByText('Tu respuesta está guardada', { exact: true }).waitFor();
    await page.screenshot({ path: path.join(out, 'facilitator-round.png'), fullPage: true });
    results.push('Next question starts empty and local draft survives offline/online transition');
    await page.getByText('Más acciones', { exact: true }).click();
    await page.getByRole('button', { name: 'Lanzar encuesta', exact: true }).click();
    await mobile.getByRole('radio', { name: '5 Excelente' }).check();
    await mobile.getByRole('button', { name: 'Enviar valoración' }).click();
    await mobile.getByText('Gracias. Tu valoración se ha guardado.', { exact: true }).waitFor();
    await mobile.screenshot({ path: path.join(out, 'participant-survey.png'), fullPage: true });
    results.push('Live survey updates and acknowledges response');
    fs.writeFileSync(path.join(out, 'results.json'), JSON.stringify({ realApi: 'http://127.0.0.1:5139', realDatabase: 'frameit_uiux_review (disposable)', sessionId: id, accessCode: session.accessCode, results }, null, 2));
    console.log(JSON.stringify({ passed: results.length, results }, null, 2));
  } finally { await browser.close(); }
}
main().catch(e => { console.error(e); process.exitCode = 1; });
