// <auto-generated />
using System;
using FrameIt.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FrameIt.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260909105953_AddQuestionRoundContext")]
    partial class AddQuestionRoundContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FrameIt.Api.Data.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Industry = "Consulting",
                            Name = "Contoso"
                        });
                });

            modelBuilder.Entity("FrameIt.Api.Data.DynamicTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FacilitatorGuidance")
                        .HasColumnType("text");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("DynamicTemplates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Audience = "Negocio + IT",
                            FacilitatorGuidance = "Mantén el foco en decisiones y aparca excepciones como pendientes.",
                            IsBuiltIn = true,
                            Key = "m365-governance-workshop",
                            Objective = "Alinear decisiones de colaboración, permisos y acceso externo para un piloto de Microsoft 365.",
                            Title = "M365 Governance Discovery",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 4, 13, 15, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("FrameIt.Api.Data.ParticipantQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("RoundContextJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("SessionParticipantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkshopSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionParticipantId");

                    b.HasIndex("WorkshopSessionId");

                    b.ToTable("ParticipantQuestions");
                });

            modelBuilder.Entity("FrameIt.Api.Data.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "Code")
                        .IsUnique();

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            ClientId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "M365-GOV",
                            Name = "M365 Governance Rollout"
                        });
                });

            modelBuilder.Entity("FrameIt.Api.Data.QuestionResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionParticipantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionQuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SessionParticipantId");

                    b.HasIndex("SessionQuestionId");

                    b.ToTable("QuestionResponses");
                });

            modelBuilder.Entity("FrameIt.Api.Data.SessionAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<Guid>("SessionParticipantId")
                        .HasColumnType("uuid");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("UploadedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("WorkshopSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionParticipantId");

                    b.HasIndex("WorkshopSessionId");

                    b.ToTable("SessionAttachments");
                });

            modelBuilder.Entity("FrameIt.Api.Data.SessionOutcome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkshopSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkshopSessionId");

                    b.ToTable("SessionOutcome");
                });

            modelBuilder.Entity("FrameIt.Api.Data.SessionParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkshopSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkshopSessionId");

                    b.ToTable("SessionParticipants");
                });

            modelBuilder.Entity("FrameIt.Api.Data.SessionQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SessionSectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SessionSectionId");

                    b.ToTable("SessionQuestion");
                });

            modelBuilder.Entity("FrameIt.Api.Data.SessionSatisfactionResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionParticipantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkshopSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionParticipantId");

                    b.HasIndex("WorkshopSessionId", "SessionParticipantId")
                        .IsUnique();

                    b.ToTable("SessionSatisfactionResponses");
                });

            modelBuilder.Entity("FrameIt.Api.Data.SessionSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkshopSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkshopSessionId");

                    b.ToTable("SessionSection");
                });

            modelBuilder.Entity("FrameIt.Api.Data.TemplateQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("TemplateSectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TemplateSectionId");

                    b.ToTable("TemplateQuestion");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Key = "work-documents",
                            Kind = 2,
                            OptionsJson = "[]",
                            Order = 1,
                            Prompt = "¿Qué tipo de documentos usáis y cuáles cambian a menudo?",
                            SettingsJson = "{\"maxItems\":\"6\"}",
                            TemplateSectionId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Title = "Documentos actuales"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Key = "sharing-pain",
                            Kind = 1,
                            OptionsJson = "[]",
                            Order = 2,
                            Prompt = "¿Qué problemas tenéis hoy al compartir y encontrar información?",
                            SettingsJson = "{}",
                            TemplateSectionId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Title = "Problemas actuales"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Key = "external-access",
                            Kind = 4,
                            OptionsJson = "[{\"Id\":\"green\",\"Label\":\"Permitido\",\"Description\":null},{\"Id\":\"yellow\",\"Label\":\"Permitido con control\",\"Description\":null},{\"Id\":\"red\",\"Label\":\"No permitido\",\"Description\":null}]",
                            Order = 1,
                            Prompt = "¿Cuál debe ser la postura base ante el acceso externo en el piloto?",
                            SettingsJson = "{\"selectionMode\":\"single\"}",
                            TemplateSectionId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Title = "Semáforo del acceso externo"
                        });
                });

            modelBuilder.Entity("FrameIt.Api.Data.TemplateSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DynamicTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DynamicTemplateId");

                    b.ToTable("TemplateSection");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            DynamicTemplateId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Key = "current-state",
                            Objective = "Capturar cómo trabaja hoy el equipo.",
                            Order = 1,
                            Title = "Mapa del trabajo real"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            DynamicTemplateId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Key = "governance",
                            Objective = "Acordar lo que sí y no entra en el piloto.",
                            Order = 2,
                            Title = "Gobernanza y límites"
                        });
                });

            modelBuilder.Entity("FrameIt.Api.Data.WorkshopSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid?>("ActiveQuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActiveSectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<int>("Phase")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<bool>("ResultsVisible")
                        .HasColumnType("boolean");

                    b.Property<bool>("RoundOpen")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("RoundOpenedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SatisfactionSurveyOpen")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("SessionStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("TracksSessionTime")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccessCode")
                        .IsUnique();

                    b.HasIndex("ClientId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TemplateId");

                    b.ToTable("WorkshopSessions");
                });

            modelBuilder.Entity("FrameIt.Api.Data.ParticipantQuestion", b =>
                {
                    b.HasOne("FrameIt.Api.Data.SessionParticipant", "SessionParticipant")
                        .WithMany()
                        .HasForeignKey("SessionParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrameIt.Api.Data.WorkshopSession", "WorkshopSession")
                        .WithMany("ParticipantQuestions")
                        .HasForeignKey("WorkshopSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionParticipant");

                    b.Navigation("WorkshopSession");
                });

            modelBuilder.Entity("FrameIt.Api.Data.Project", b =>
                {
                    b.HasOne("FrameIt.Api.Data.Client", "Client")
                        .WithMany("Projects")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("FrameIt.Api.Data.QuestionResponse", b =>
                {
                    b.HasOne("FrameIt.Api.Data.SessionParticipant", "SessionParticipant")
                        .WithMany("Responses")
                        .HasForeignKey("SessionParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrameIt.Api.Data.SessionQuestion", "SessionQuestion")
                        .WithMany("Responses")
                        .HasForeignKey("SessionQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionParticipant");

                    b.Navigation("SessionQuestion");
                });

            modelBuilder.Entity("FrameIt.Api.Data.SessionAttachment", b =>
                {
                    b.HasOne("FrameIt.Api.Data.SessionParticipant", "SessionParticipant")
                        .WithMany()
                        .HasForeignKey("SessionParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrameIt.Api.Data.WorkshopSession", "WorkshopSession")
                        .WithMany("Attachments")
                        .HasForeignKey("WorkshopSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionParticipant");

                    b.Navigation("WorkshopSession");
                });

            modelBuilder.Entity("FrameIt.Api.Data.SessionOutcome", b =>
                {
                    b.HasOne("FrameIt.Api.Data.WorkshopSession", "WorkshopSession")
                        .WithMany("Outcomes")
                        .HasForeignKey("WorkshopSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkshopSession");
                });

            modelBuilder.Entity("FrameIt.Api.Data.SessionParticipant", b =>
                {
                    b.HasOne("FrameIt.Api.Data.WorkshopSession", "WorkshopSession")
                        .WithMany("Participants")
                        .HasForeignKey("WorkshopSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkshopSession");
                });

            modelBuilder.Entity("FrameIt.Api.Data.SessionQuestion", b =>
                {
                    b.HasOne("FrameIt.Api.Data.SessionSection", "SessionSection")
                        .WithMany("Questions")
                        .HasForeignKey("SessionSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionSection");
                });

            modelBuilder.Entity("FrameIt.Api.Data.SessionSatisfactionResponse", b =>
                {
                    b.HasOne("FrameIt.Api.Data.SessionParticipant", "SessionParticipant")
                        .WithMany()
                        .HasForeignKey("SessionParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrameIt.Api.Data.WorkshopSession", "WorkshopSession")
                        .WithMany("SatisfactionResponses")
                        .HasForeignKey("WorkshopSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionParticipant");

                    b.Navigation("WorkshopSession");
                });

            modelBuilder.Entity("FrameIt.Api.Data.SessionSection", b =>
                {
                    b.HasOne("FrameIt.Api.Data.WorkshopSession", "WorkshopSession")
                        .WithMany("Sections")
                        .HasForeignKey("WorkshopSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkshopSession");
                });

            modelBuilder.Entity("FrameIt.Api.Data.TemplateQuestion", b =>
                {
                    b.HasOne("FrameIt.Api.Data.TemplateSection", "TemplateSection")
                        .WithMany("Questions")
                        .HasForeignKey("TemplateSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TemplateSection");
                });

            modelBuilder.Entity("FrameIt.Api.Data.TemplateSection", b =>
                {
                    b.HasOne("FrameIt.Api.Data.DynamicTemplate", "DynamicTemplate")
                        .WithMany("Sections")
                        .HasForeignKey("DynamicTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DynamicTemplate");
                });

            modelBuilder.Entity("FrameIt.Api.Data.WorkshopSession", b =>
                {
                    b.HasOne("FrameIt.Api.Data.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrameIt.Api.Data.Project", "Project")
                        .WithMany("Sessions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrameIt.Api.Data.DynamicTemplate", "Template")
                        .WithMany("Sessions")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Project");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("FrameIt.Api.Data.Client", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("FrameIt.Api.Data.DynamicTemplate", b =>
                {
                    b.Navigation("Sections");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("FrameIt.Api.Data.Project", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("FrameIt.Api.Data.SessionParticipant", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("FrameIt.Api.Data.SessionQuestion", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("FrameIt.Api.Data.SessionSection", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("FrameIt.Api.Data.TemplateSection", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("FrameIt.Api.Data.WorkshopSession", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Outcomes");

                    b.Navigation("ParticipantQuestions");

                    b.Navigation("Participants");

                    b.Navigation("SatisfactionResponses");

                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
