import { useEffect, useRef } from 'react'
import { Link } from 'react-router-dom'
import { Brand } from '../components/Brand'
import { LegalFooter } from '../components/LegalFooter'

type LegalKind = 'notice' | 'privacy' | 'cookies'
const titles = { notice: 'Aviso legal y condiciones de uso', privacy: 'Política de privacidad', cookies: 'Cookies y almacenamiento de sesión' }

function Company() {
  return <dl><dt>Titular</dt><dd>OLATIC GROUP SOLUTIONS, S.L. · NIF B95800488</dd><dt>Domicilio</dt><dd>C/ Andrés Eliseo de Mañaricua 15, 48003 Bilbao, Bizkaia, España.</dd><dt>Contacto</dt><dd><a href="mailto:info@olatic.es">info@olatic.es</a> · <a href="tel:+34944362257">944 362 257</a></dd></dl>
}

function Notice() {
  return <><h2>Quién está detrás de FrameIt</h2><Company /><p>Datos corporativos publicados en el <a href="https://olatic.es/aviso-legal.html">aviso legal de OLATIC</a>. FrameIt permite preparar talleres, participar en rondas y conservar su documentación.</p>
    <h2>Uso del servicio</h2><p>Accede únicamente a sesiones a las que hayas sido invitado. Protege los códigos de entrada y las credenciales de facilitador. No introduzcas contenidos ilícitos, dañinos o que vulneren derechos de otras personas, ni intentes acceder a información ajena o interferir con el servicio.</p><p>Los ejemplos de la landing son ilustrativos. Las condiciones de prestación del servicio que se acuerden con OLATIC regirán la relación contractual; navegar por esta web no supone contratar un plan de pago.</p>
    <h2>Contenidos y propiedad intelectual</h2><p>La interfaz, la marca y los materiales de FrameIt corresponden a OLATIC o a sus respectivos titulares. El acceso no transfiere sus derechos. Las aportaciones al taller conservan los derechos de sus titulares: quien las comparte debe contar con autorización para su uso, visualización y documentación en la sesión.</p>
    <h2>Diseño y documentación con IA</h2><p>Cuando esté habilitada, la asistencia de IA puede proponer plantillas de dinámicas y generar resúmenes a partir del contenido del taller. Estos resultados pueden contener errores y deben revisarse antes de usarlos o compartirlos. La herramienta no sustituye el criterio del facilitador ni toma decisiones sobre las personas.</p>
    <h2>Disponibilidad y enlaces</h2><p>El servicio puede requerir mantenimiento y sufrir incidencias. OLATIC atiende los avisos recibidos en su dirección de contacto. Los enlaces externos conducen a sitios con sus propias condiciones. Nada de lo indicado limita las responsabilidades o derechos que resulten exigibles por ley.</p>
    <h2>Normativa aplicable</h2><p>Se aplica la normativa española y europea que corresponda, y los tribunales competentes según la ley. Consulta también nuestra <Link to="/privacidad">política de privacidad</Link> y la información sobre <Link to="/cookies">cookies</Link>.</p></>
}

function Privacy() {
  return <><h2>Responsable y contacto</h2><Company /><p>OLATIC gestiona el sitio y el acceso al servicio. Si participas en un taller organizado por otra entidad, esta determina la finalidad del taller y debe informarte de la base jurídica y las condiciones de tratamiento de tus aportaciones. OLATIC actúa por cuenta de esa entidad cuando presta el servicio como encargado. Puedes consultar quién organiza tu sesión al facilitador.</p>
    <h2>Qué información se utiliza</h2><ul><li>Facilitadores: identificación de usuario, credenciales protegidas, verificación de acceso y sesiones de autenticación.</li><li>Participantes: nombre o alias, identificador de sesión, respuestas, preguntas, archivos y valoraciones que decidas enviar.</li><li>Talleres: información de clientes, proyectos, preguntas, resultados y documentación.</li><li>Navegación y soporte: datos técnicos necesarios para comunicarte con el servicio y la información que facilites al contactar con OLATIC.</li></ul><p>El código permite localizar el taller; el alias es necesario para participar. No necesitas una cuenta de facilitador. El modo de lectura permite seguir la sesión sin enviar aportaciones. Que una respuesta se muestre sin nombre no implica que sus datos se hayan eliminado o anonimizado en el sistema.</p>
    <h2>Para qué se tratan y con qué base</h2><p>El acceso de facilitadores y la prestación acordada con el cliente se gestionan para ejecutar la relación contractual. La atención de solicitudes se basa en las medidas previas a la contratación o en el interés legítimo de responderlas. La protección del servicio y la prevención de abusos responden al interés legítimo de mantenerlo seguro; las obligaciones legales se atienden cuando son aplicables.</p><p>La entidad organizadora debe determinar la base que legitima la participación en cada taller. Entrar en una sesión o leer este aviso no equivale a consentir publicidad ni otros usos ajenos al taller.</p>
    <h2>Quién puede ver los datos</h2><p>El facilitador accede a los contenidos de su sesión. Otros participantes o lectores pueden ver lo que se publique según la configuración del taller. El organizador puede exportar su documentación y compartirla con los destinatarios del taller. Utiliza un alias si no necesitas mostrar tu nombre y evita datos sensibles o información de terceros innecesaria.</p><p>Los proveedores de alojamiento, almacenamiento, soporte y, cuando esté habilitado, generación de resúmenes con IA pueden tratar los datos necesarios para esas funciones. No se incorporan herramientas de publicidad o analítica a esta versión de FrameIt.</p>
    <h2>IA y servicios externos</h2><p>Si la generación asistida está configurada, al solicitar la documentación se envía contenido de la sesión al proveedor de IA configurado. Al utilizar el diseñador asistido se envían las instrucciones, el historial reciente y el borrador o ámbito seleccionado; FrameIt no guarda esa conversación al salir del diseñador. Consulta al organizador antes de aportar información que no deba procesarse de ese modo. Los resultados requieren revisión humana y no se utilizan aquí para decisiones automatizadas con efectos jurídicos sobre participantes.</p><p>Las fuentes de la interfaz operativa se descargan de Google Fonts, lo que comunica al proveedor datos de conexión, como la dirección IP. Puedes consultar su <a href="https://policies.google.com/privacy?hl=es">política de privacidad</a>.</p><p>Para conocer los proveedores concretos de tu taller, su ubicación y, si corresponde, las garantías de una transferencia fuera del Espacio Económico Europeo, contacta con OLATIC. La <a href="https://olatic.es/privacidad.html">política corporativa</a> recoge el marco general de tratamiento por proveedores.</p>
    <h2>Durante cuánto tiempo</h2><p>Los contenidos se conservan para gestionar y documentar el taller durante la relación de servicio y conforme a las instrucciones de su organizador; después se atienden las obligaciones de conservación y las responsabilidades aplicables. Cerrar la ronda, la sesión o el navegador no elimina lo enviado al servidor. Solicita al organizador o a OLATIC el plazo aplicable a tu taller o la supresión que proceda.</p><p>Los plazos del almacenamiento en tu navegador se detallan en la <Link to="/cookies">política de cookies</Link>.</p>
    <h2>Tus derechos</h2><p>Puedes solicitar acceso, rectificación, supresión, oposición, limitación o portabilidad, cuando procedan, escribiendo a <a href="mailto:info@olatic.es">info@olatic.es</a>. Indica la sesión y tu relación con ella para localizar la solicitud; se podrá pedir la información necesaria para verificar tu identidad. Si el tratamiento depende de tu consentimiento, puedes retirarlo sin afectar a la licitud del tratamiento anterior. Cuando otra entidad sea responsable del taller, te ayudaremos a dirigirle la petición.</p><p>También puedes reclamar ante la <a href="https://www.aepd.es/">Agencia Española de Protección de Datos</a>.</p></>
}

function Cookies() {
  return <><p>FrameIt utiliza mecanismos propios de acceso, seguridad y continuidad del taller. Esta versión no instala cookies de analítica o publicidad. Las cookies técnicas destinadas al servicio solicitado no necesitan una aceptación opcional para funcionar.</p>
    <h2>Cookies propias</h2><dl><dt>frameit.facilitator.v1</dt><dd>Mantiene el acceso autenticado del facilitador. Cookie de sesión; la autorización del servidor caduca como máximo a las 8 horas, sin renovación deslizante.</dd><dt>frameit.pending.v1</dt><dd>Enlaza los pasos de verificación del acceso. Dura hasta 15 minutos y se elimina al completar o cancelar el proceso; el reto de inicio de sesión caduca a los 5 minutos.</dd><dt>frameit.csrf.v1</dt><dd>Protege los formularios y operaciones privadas frente a solicitudes falsificadas. Cookie de sesión del navegador.</dd></dl><p>Son mecanismos de FrameIt operados por OLATIC; se utilizan al solicitar las funciones de acceso y seguridad correspondientes.</p>
    <h2>Almacenamiento de la pestaña</h2><dl><dt>frameit.participant:…</dt><dd>Recuerda la identidad de participación para recuperar tu entrada al recargar.</dd><dt>frameit.answer:…</dt><dd>Conserva temporalmente borradores, el estado de envío y la valoración de la sesión.</dd><dt>frameit.question-notifications:…</dt><dd>Recuerda las preguntas vistas y los avisos pendientes del facilitador.</dd></dl><p>Estos datos se guardan en sessionStorage durante la sesión de la pestaña. El navegador suele eliminarlos al cerrarla, aunque sus funciones de restauración pueden recuperarlos. No se usan para seguirte entre sitios. Eliminar estos datos no borra las aportaciones ya enviadas al taller.</p>
    <h2>Cómo gestionarlos</h2><p>Puedes consultar, bloquear o eliminar los datos del sitio desde los ajustes de privacidad de tu navegador. Bloquear las cookies técnicas puede impedir el acceso privado; borrar el almacenamiento de la pestaña puede hacer que pierdas borradores o la recuperación de tu participación.</p><p>No hay categorías opcionales que aceptar o rechazar en esta versión. Si se incorporan herramientas no necesarias, esta información y los controles de consentimiento deberán actualizarse antes de activarlas.</p>
    <h2>Más información</h2><p>Consulta la <Link to="/privacidad">privacidad de FrameIt</Link> o contacta con <a href="mailto:info@olatic.es">info@olatic.es</a>. La <a href="https://olatic.es/cookies.html">política de cookies de olatic.es</a> corresponde al sitio corporativo; su inventario no es el de FrameIt.</p></>
}

export function LegalPage({ kind }: { kind: LegalKind }) {
  const heading = useRef<HTMLHeadingElement>(null)
  useEffect(() => {
    const previousTitle = document.title
    document.title = `${titles[kind]} · FrameIt`
    window.scrollTo(0, 0)
    heading.current?.focus({ preventScroll: true })
    return () => { document.title = previousTitle }
  }, [kind])
  return <div className="legal-page"><header className="legal-header"><Link to="/" aria-label="FrameIt, inicio"><Brand /></Link><Link to="/">Volver al inicio</Link></header><main className="legal-content"><h1 ref={heading} tabIndex={-1}>{titles[kind]}</h1><p className="legal-date">Actualizado el 10 de septiembre de 2026</p>{kind === 'notice' ? <Notice /> : kind === 'privacy' ? <Privacy /> : <Cookies />}</main><LegalFooter /></div>
}
